sudo: required
services:
  - docker

before_install:
  - docker build -t tommyling79/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true tommyling79/react-test npm run test

after_success:
  - docker build -t tommyling79/multi-client ./client
  - docker build -t tommyling79/multi-nginx ./nginx
  - docker build -t tommyling79/multi-server ./server
  - docker build -t tommyling79/multi-worker ./worker