sudo: required
services:
  - docker

before_install:
  - docker build -t tommyling79/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true tommyling79/react-test npm run test

after_success:
  - docker build -t tommyling79/multi-client ./client
  - docker build -t tommyling79/multi-nginx ./nginx
  - docker build -t tommyling79/multi-server ./server
  - docker build -t tommyling79/multi-worker ./worker

  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push tommyling79/multi-client
  - docker push tommyling79/multi-nginx
  - docker push tommyling79/multi-server
  - docker push tommyling79/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'multi-docker'
  env: 'Multidocker-env'
  bucket_name: 'elasticbeanstalk-us-east-2-765793169048'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY